### ISSUE TITLE
User Profile Section Appears Behind Sidebar Instead of on Top

### ISSUE THREAD

**Issue by ShivamJha2436** [ShivamJha2436/Notion_Clone#11]
Issue Description:

When clicking on the user profile section in the sidebar, it currently appears behind the sidebar content instead of on top of it as intended. This results in the user profile section being obscured by the sidebar content, making it inaccessible to users.

Expected Behavior:

The user profile section should overlay on top of the sidebar content when clicked, allowing users to access their profile information without interference from the sidebar content.

Steps to Reproduce:

Navigate to the sidebar.
Click on the user profile section.

**Comment by kusumdesai** [comment]
Hey @ShivamJha2436 !!
Please assign this to me under GSSoC'24.
